Spanish translation
Cimmerian-Iter/KyuHEN-translation pull request #1
Opened 2021-04-09 13:45 UTC by RY0M43CH1Z3N

2021-04-09 14:37 UTC, m1s3ry requested changes

2021-04-09 14:37 UTC, m1s3ry commented on es-ES.js
> +			desc: 'Crea un juego con una motor existente a tu elección, por ejemplo: GameMaker o Unity.',
"...con un* motor existente...

2021-04-09 14:37 UTC, m1s3ry commented on es-ES.js
> +			desc: 'Crea un juego desde 0 con tu motor y compliado con vitaSDK o dolceSDK.',
...y compilado* con...

2021-04-09 14:37 UTC, m1s3ry commented on es-ES.js
> +			'Los desarrolladores pueden presentar todo lo que quieran pero soo podrán ganar un premio por categoría.',
'Los desarrolladores pueden presentar más de una entrada, pero solo podrán ganar un premio por categoría.'

2021-04-09 14:37 UTC, m1s3ry commented on es-ES.js
> +			title: 'Primer juego',
'Juego 1' would make more sense

2021-04-09 14:37 UTC, m1s3ry commented on es-ES.js
> +			title: 'Segundo juego',
'Juego 2' would make more sense

2021-04-09 14:37 UTC, m1s3ry commented on es-ES.js
> +			'Si el juego que quieres enviar ya había salido en PS Vita, debe quedar en estado de prototipo y tener mejoras respecto al anterior para que sea un juego completo. Para las herramientas, los cambi
'debe quedar en estado de prototipo' is incorrect, it should be 'tuvo que ser en estado de prototipo'

'Para las herramientas, los cambios deben ser consecuentes ya que los homebrew/plugins requieren mucho trabajo.' doesn't make sense, even though the original text doesn't make much sense either lol. 
Try with 'Para los plugins o herramientas, los cambios deben ser significativos y consecuentes respecto a las versiones anteriores.'
This does change the meaning of the original phrase to "for plugins and tools, the changes must be significative and consecuent to the previous versions" tho.

2021-04-09 14:37 UTC, m1s3ry commented on es-ES.js
> +			'No se permite la piratería. No se acepta el uso de bienes con copyright, los juegos deben ser creaciones originales. Permitimos el uso de bienes genéricos gratuitos, por ejemplo, los puedes encon
''No se permite la piratería. No se acepta el uso de archivos bajo copyright, los juegos deben ser creaciones originales. Permitimos el uso de recursos genéricos gratuitos, como los que puedes encontrar en la tienda de Unity, pero se valorará más los hechos a mano. Para los ports, no incluyas los datos del juego si no se pueden compartir. Motores hechos a base de RE (Ingeniería reversa) están permitidos, pero los motores hechos con código fuente filtrado/ilegal no están permitido.'

2021-04-09 14:37 UTC, m1s3ry commented on es-ES.js
> +		paypal: 'Debes de tener una cuenta de paypal para recibir el premio.',
'Debes tener'

2021-04-09 14:37 UTC, m1s3ry commented on es-ES.js
> +			'Puedes publicar versiones públicas fuera de nuestra web cuando hayamos comprobado que ya has mostrado tu proyecto en nuestra web',
'...fuera de nuestra web una vez que hayamos aprobado tu proyecto'

2021-04-09 14:37 UTC, m1s3ry commented on es-ES.js
> +			'Tienes que incluir la pantalla del concurso en el proceso de arranque de tu homebrew (puedes incluirlo en el asset del live area. Los plugins obviamente no pueden mostrar la pantalla, así que te
'Tienes que incluir el logo del concurso cuando inicia tu homebrew (puedes incluirlo como imagen en el livearea). Los plugins obviamente no tienen livearea ni splashscreen, así que te pedimos que menciones el concurso kyûHEN dentro del léeme del repositorio.',

2021-04-09 14:37 UTC, m1s3ry commented on es-ES.js
> +			'Si tu proyecto está basado en un proyecto de código abierto, debes seguir usando la licencia del proyecto de código abierto',
'...debes seguir usando su licencia correspondiente'

2021-04-09 14:37 UTC, m1s3ry commented on es-ES.js
> +		cheats: 'Si comprobamos que haces trampas, serás expulsado del concurso de inmediato.',
'Si detectamos* que hiciste* trampa*, serás...'

2021-04-09 14:37 UTC, m1s3ry commented on es-ES.js
> +			'Los premios de las categorías pueden estar sujetos a pequeños cambios dependiendo de los proyectos y de la cantidad monetaria recolectada.',
'...dependiendo de la cantidad de proyectos y dinero recolectado'

2021-04-09 14:37 UTC, m1s3ry commented on es-ES.js
> +			slogan: 'El que pueda crear lo mejor',
'Quién puede crear mejor?' would be the correct translation
Still, don't fucking translate an slogan

2021-04-09 14:52 UTC, Cimmerian-Iter commented
I know that translating is hard, but that is not a reason to rush the translation. I would ask you please to take your time and instead make sure it's ready to be pushed

2021-04-10 10:19 UTC, closed without merging

2021-04-10 10:20 UTC, RY0M43CH1Z3N commented
Please review the @IlDucci translation PR: https://github.com/Cimmerian-Iter/KyuHEN-translation/pull/2